version: 2

updates:

  # Keep dependencies for GitHub Actions up-to-date
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  # Keep npm dependencies up-to-date
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/template'
      - '/exercises/practice/*'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0 # disable general npm updates
    groups:
      # Group npm security updates enabled through Exercism settings
      security-updates:
        applies-to: 'security-updates'
        patterns:
          - '*'
